version: "2"

services:
  mangospot:
    build: .
    ports:
      - 8080:80
    volumes:
      - ./000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./apache2.conf:/etc/apache2/apache2.conf
    environment:
      DB_HOST: "localhost"
      DB_USER: radius
      DB_PASSWORD: "radius"
      DB_DATABASE: radius
